### ISSUE TITLE
Question on attention replacement

### ISSUE THREAD

**Issue by wendashi** [unity-research/IP-Adapter-Instruct#4]
Thanks for your awesome work 💗💗💗, I am curious why every two adjacent MMDiT blocks in SD3 need to be replaced with different attention in IP-Adapter for SD3?  (one is original JointAttnProcessor2_0, while another is IPJointAttnProcessor2_0)

As for IP-Adapter for SD1.5/SDXL, only replace the cross-attention, while maintain the original self-attention. But, the attention of 24 blocks in the SD3 pipeline source code are the same, all are joint attention. Why don't replace them all? 🙏

/path/to/IP-Adapter-Instruct/ip_adapter/ip_adapter_instruct.py

``` 
class IPAdapter_sd3_Instruct (IPAdapter_sd3):
...
     def set_ip_adapter(self, n=2):
...
            if i % n == 0 or i == 0:  # Apply IPJointAttnProcessor2_0 to every nth block
                attn_procs[name] = IPJointAttnProcessor2_0(
                    hidden_size=hidden_size,
                    cross_attention_dim=self.pipe.transformer.config.caption_projection_dim,
                    scale=1.0,
                    num_tokens=self.num_tokens,
                    num_heads=12,
                ).to(self.device, dtype=torch.float16)
                attn_procs[name].load_state_dict(weights,strict=False)


            else:  # Use JointAttnProcessor2_0 for other blocks
                attn_procs[name] = JointAttnProcessor2_0(
                    num_tokens=self.num_tokens,
                ).to(self.device, dtype=torch.float16)
```

**Comment by CiaraStrawberry** [comment]
Hey! Good question! Vram reasons mostly, since the whole model is made out MMDiT blocks, adding the IP Adapter cross attention adds a rather disproportionate amount of required vram vs with sd 1.5 or sdxl, so every other block seemed like a good balance between not causing too many potential problems, but without using too much vram
